const fs = require('fs');
const path = require('path');
const sqlite3 = require('sqlite3').verbose();

// 1. Setup a fake browser environment to eval the old standalone JS
global.window = {};
global.localStorage = {
  store: {},
  getItem(k) { return this.store[k] || null; },
  setItem(k, v) { this.store[k] = v; }
};

// 2. Read and eval image manifest and db.js
try {
  const imgCode = fs.readFileSync(path.join(__dirname, '../../src/image-manifest.js'), 'utf-8');
  eval(imgCode); // Populates window.IMG
} catch(e) {
  console.error("Failed to eval image-manifest.js:", e);
}

try {
  const dbCode = fs.readFileSync(path.join(__dirname, '../../src/db.js'), 'utf-8');
  eval(dbCode); // Populates window.DB and runs seed()
} catch(e) {
  console.error("Failed to eval db.js:", e);
}

// Extract the rich prototype data generated by db.js
const DB = global.window.DB;
const categories = DB.categories.getAll();
const brands = DB.brands.getAll();
const merchants = DB.merchants.getAll();
const products = DB.products.getAll();

console.log(`Extracted: ${categories.length} categories, ${brands.length} brands, ${merchants.length} merchants, ${products.length} products.`);

// 3. Insert into SQLite
const dbPath = path.join(__dirname, '../designer_sale.sqlite');
const db = new sqlite3.Database(dbPath, (err) => {
  if (err) {
    console.error("Error opening db:", err);
    process.exit(1);
  }
});

db.serialize(() => {
  console.log("Emptying tables...");
  db.run("DELETE FROM products");
  db.run("DELETE FROM brands");
  db.run("DELETE FROM merchants");
  db.run("DELETE FROM categories");

  console.log("Seeding full prototype data...");
  
  // Insert Categories
  const catStmt = db.prepare("INSERT INTO categories (id, label) VALUES (?, ?)");
  categories.forEach(c => catStmt.run(c.id, c.label));
  catStmt.finalize();

  // Insert Brands
  const brandStmt = db.prepare("INSERT INTO brands (id, name, description, website, founded, country) VALUES (?, ?, ?, ?, ?, ?)");
  brands.forEach(b => brandStmt.run(b.id, b.name, b.description || '', b.website || '', b.founded || '', b.country || 'AU'));
  brandStmt.finalize();

  // Insert Merchants
  const merchStmt = db.prepare("INSERT INTO merchants (id, name, state, city, online, inStore, focus, email, phone, website, description) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
  merchants.forEach(m => merchStmt.run(m.id, m.name, m.state || '', m.city || '', m.online ? 1 : 0, m.inStore ? 1 : 0, m.focus || '', m.email || '', m.phone || '', m.website || '', m.description || ''));
  merchStmt.finalize();

  // Insert Products
  const prodStmt = db.prepare("INSERT INTO products (id, category, title, brandId, merchantId, rrp, sale, discountPct, newIn, sizes, image, added, description) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
  
  // We don't save placeholder to DB as the frontend handles fallback now
  products.forEach(p => {
    prodStmt.run(
      p.id, p.category, p.title, p.brandId, p.merchantId, 
      p.rrp, p.sale, p.discountPct, p.newIn ? 1 : 0, 
      JSON.stringify(p.sizes || []), p.image || null, p.added || Date.now(), p.description || ''
    );
  });
  prodStmt.finalize();

  console.log("Migration complete!");
});

db.close();
